---
- name : Configure Docker on EC2 Instances
  hosts : all
  become : true
  tasks :
  - name : updating apt
    command : sudo apt update

  - name : install docker
    command : sudo apt install -y docker.io

  - name : run Docker service
    command : sudo systemctl start docker

  - name : to deploy finance-me container
    command : sudo docker run -itd -p 8081:8080 --name insure-me macintosh2023/insure-me:1.0
















